### PR TITLE
Fix issue #3 from updated API, add Energy tab support

### PR DESCRIPTION
**Pull request by jeffkibuule**
Changes:
- Fix issue #3 by renaming use of `spaces` in project to `circuits` due to updated API redirecting to `api/v1/circuits` from `api/v1/spaces`
- Add Home Assistant Energy tab support for individual circuits
- Bump version to `0.0.4`

Testing:
- Verified on personal SPAN installation running firmware `spanos2/r202223/03`

### CODE REVIEW

**Comment by jeffkibuule** [comment]
@galak Anything you'd like to see me do in this PR?

**Comment by galak** [comment]
> @galak Anything you'd like to see me do in this PR?

We'll it would be nice to support both the old and new API.  Since some of us are still on the older firmware.

**Comment by jeffkibuule** [comment]
Ok, I'll noodle on that a bit.

**Comment by jeffkibuule** [comment]
It looks like @wez added support for older firmware, any chance we can get this merged in?

**Comment by galak** [comment]
> It looks like @wez added support for older firmware, any chance we can get this merged in?

Sorry, I missed that will try and take a look soon.

**Comment by wez** [comment]
Note that I don't have the older firmware, so it is purely a speculative change. The logic does work for my more recent firmware.

**Comment by jeffkibuule** [comment]
Bumping this thread.

**Comment by nathan-curtis** [comment]
any news on merging this - I have two week old panels (no choice, they came installed with the newer secure firmware) and had to use Jeff's branch (thank you) to get them to onboard.  I've got some issues popping with a few items in the logs (switch domain stuff - looks like you're trying to setup the on/off from the breakers, and input select or select domain stuff - trying to set the prioritization?) failing, but I'd rather go back to main branch before seeing if the issue is there too...

**Review by galak — APPROVED** [review]

**Pull request merged**
